language: node_js
sudo: required

services:
  - docker

install: true
notifications:
  email: false

os: linux
dist: bionic
node_js:
  - 12

branches:
  only:
    - setup-cd

script:
  - npm install -g @angular/cli

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: setup-cd
